package:
  name: ccpi-framework
  version: 0.11.3


build:
  preserve_egg_dir: False
#script_env:
#    - CIL_VERSION   
  number: 0
  
  
test:
  requires:
    - python-wget
    - cvxpy # [not win]
    - h5py
    
requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - h5py
  
about:
  home: http://www.ccpi.ac.uk
  license:  Apache 2.0 License
  summary: 'CCPi Framework'
